server:
    port: 8082
    
spring:
    application:
        name: discoveryserver
    profiles:
        active: testprofile
 
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/
        register-with-eureka: false
        fetch-registry: false