server:
    port: 8080
    
spring:
    application:
        name: gateway
    profiles:
        active: testprofile
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/