server:
    port: 8083
    
spring:
    application:
        name: radio-service
    profiles:
        active: testprofile
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/